//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema_DB_Kursach_Net
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film_Session_Hall
    {
        public string hall_name { get; set; }
        public string type { get; set; }
        public int capacity { get; set; }
        public int id_cinema { get; set; }
        public string fIlm_name { get; set; }
        public string genre { get; set; }
        public string country { get; set; }
        public string age_rating { get; set; }
        public int id_session { get; set; }
        public System.DateTime date { get; set; }
        public int duration { get; set; }
        public int id_hall { get; set; }
        public int id_film { get; set; }
    }
}
