//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema_DB_Kursach_Net
{
    using System;
    using System.Collections.Generic;
    
    public partial class Full_Session
    {
        public string cinema_name { get; set; }
        public string address { get; set; }
        public string cinema_contact { get; set; }
        public Nullable<int> id_film { get; set; }
        public string film_name { get; set; }
        public string genre { get; set; }
        public string country { get; set; }
        public string age_rating { get; set; }
        public Nullable<int> id_cinema { get; set; }
        public Nullable<int> capacity { get; set; }
        public string type { get; set; }
        public string hall_name { get; set; }
        public Nullable<int> id_hall { get; set; }
        public int duration { get; set; }
        public System.DateTime date { get; set; }
        public int id_session { get; set; }
        public Nullable<int> id_ticket { get; set; }
        public Nullable<int> price { get; set; }
        public string status { get; set; }
        public Nullable<int> id_client { get; set; }
        public string client_name { get; set; }
        public string cilent_surname { get; set; }
        public string client_contact { get; set; }
    }
}
