//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema_DB_Kursach_Net
{
    using System;
    using System.Collections.Generic;
    
    public partial class Full_Ticket
    {
        public Nullable<int> id { get; set; }
        public string name { get; set; }
        public string genre { get; set; }
        public string country { get; set; }
        public string age_rating { get; set; }
        public Nullable<int> id_session { get; set; }
        public Nullable<int> duration { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> id_hall { get; set; }
        public string hall_name { get; set; }
        public string type { get; set; }
        public Nullable<int> capacity { get; set; }
        public Nullable<int> id_cinema { get; set; }
        public string cinema_name { get; set; }
        public string address { get; set; }
        public string contact { get; set; }
        public int id_ticket { get; set; }
        public int price { get; set; }
        public string status { get; set; }
        public Nullable<int> id_client { get; set; }
        public string client_name { get; set; }
        public string surname { get; set; }
        public string client_contact { get; set; }
    }
}
