//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema_DB_Kursach_Net
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int id { get; set; }
        public int price { get; set; }
        public string status { get; set; }
        public int id_session { get; set; }
        public Nullable<int> id_client { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Session Session { get; set; }
    }
}
